# Generated by Django 2.0 on 2019-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_origin', models.CharField(db_index=True, max_length=100, unique=True)),
                ('place_of_destination', models.CharField(db_index=True, max_length=100, unique=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('no_of_seats', models.IntegerField()),
                ('flight_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Passangers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male ', max_length=3)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('flight_id', models.CharField(max_length=64)),
            ],
        ),
    ]
